version: "3.9"

networks:
  eleicoes-api-network:
    driver: bridge

services:
  eleicoes-api-postgresql:
    image: postgres:alpine
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eleicoes
    ports:
      - "5433:5432"
    networks:
      - eleicoes-api-network

  eleicoes-api-redis:
    image: redis:6.2.1-alpine
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - eleicoes-api-network

  eleicoes-api:
    container_name: eleicoes-api-container
    build: .
    command: ["/wait-for-it.sh", "eleicoes-api-postgresql:5432", "-t", "30", "--", "java", "-jar", "api.jar"]
    ports:
      - "8080:8080"
    networks:
      - eleicoes-api-network
    depends_on:
      - eleicoes-api-postgresql
      - eleicoes-api-redis